import Layout from "@/components/Layout/Layout";
import AnimatedText from "@/components/animatedText/AnimatedText";
import NavBar from "@/components/nav/NavBar";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useRef } from "react";
import ProfileImg from "../assets/images/developer-pic-2.jpg";
import { useInView, useMotionValue, useSpring } from "framer-motion";
import Skills from "@/components/skills/Skills";
import Exprience from "@/components/about/exprience/Exprience";
import Education from "@/components/about/education/Education";

const AnimateNumbers = ({ value, className }) => {
  const ref = useRef(null);
  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, { duration: 3000 });
  const isInview = useInView(ref, { once: true });

  useEffect(() => {
    if (isInview) {
      motionValue.set(value);
    }
  }, [isInview, motionValue, springValue]);

  useEffect(() => {
    springValue.on("change", (latestValue) => {
      if (ref.current && latestValue.toFixed(0) <= value) {
        ref.current.textContent = latestValue.toFixed(0);
      }
    });
  }, [springValue, value]);

  return <span className={className} ref={ref}></span>;
};

const about = () => {
  return (
    <>
      <Head>
        <title>Niloy Kumar || About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <main className="flex w-full flex-col items-center justify-center text-dark dark:text-light bg-light dark:bg-dark">
        <Layout className="!pt-16   !mb-28">
          <AnimatedText text="Passion Fuels Purpose!" className="mb-16" />
          <div className="grid  my-4 w-full grid-cols-8 gap-16">
            {/* 1st row */}
            <div className="space-y-4 col-span-3 flex flex-col justify-start items-start">
              <h2 className="font-bold uppercase text-dark/75 dark:text-light/75">Biography</h2>

              <div className="space-y-4">
                <p className="font-medium">
                  Hi, I'm CodeBucks, a web developer and UI/UX designer with a
                  passion for creating beautiful, functional, and user-centered
                  digital experiences. With 4 years of experience in the field.
                  I am always looking for new and innovative ways to bring my
                  clients' visions to life.
                </p>

                <p className="font-medium">
                  I believe that design is about more than just making things
                  look pretty – it's about solving problems and creating
                  intuitive, enjoyable experiences for users.
                </p>

                <p className="font-medium">
                  Whether I'm working on a website, mobile app, or other digital
                  product, I bring my commitment to design excellence and
                  user-centered thinking to every project I work on. I look
                  forward to the opportunity to bring my skills and passion to
                  your next project.
                </p>
              </div>
            </div>
            {/* 2nd row */}
            <div className="space-y-4 relative h-max border-2 border-solid border-dark dark:border-light bg-light dark:bg-dark col-span-3 flex flex-col justify-start items-start rounded-2xl p-8">
              <div className="absolute w-[102%] h-[103%] top-0 -right-4 -z-10 bg-dark dark:bg-light rounded-[2rem]" />
              <Image
                src={ProfileImg}
                alt="Profile Photo"
                className="w-full h-auto rounded-2xl"
              />
            </div>

            {/* 3rd row */}
            <div className="space-y-4 col-span-2 flex flex-col items-end justify-between gap-10">
              <div className="flex flex-col items-end justify-center">
                <span className="text-7xl font-bold">
                  <AnimateNumbers className="text-7xl font-bold" value={40} />+
                </span>
                <span className="font-medium text-dark/75 dark:text-light/75 text-lg capitalize">
                  Satisfied Clients
                </span>
              </div>

              <div className="flex flex-col items-end justify-center">
                <span className="text-7xl font-bold">
                  <AnimateNumbers className="text-7xl font-bold" value={50} />+
                </span>
                <span className="font-medium text-dark/75 dark:text-light/75 text-lg capitalize">
                  Completed Projects
                </span>
              </div>

              <div className="flex flex-col items-end justify-center">
                <span className="text-7xl font-bold">
                  <AnimateNumbers className="text-7xl font-bold" value={4} />+
                </span>
                <span className="font-medium text-dark/75 dark:text-light/75 text-lg capitalize">
                  years of experience
                </span>
              </div>
            </div>
          </div>

          <Skills />

          <Exprience />
          <Education />
        </Layout>
      </main>
    </>
  );
};

export default about;
