import NavBar from "@/components/nav/NavBar";
import React, { useRef } from "react";
import Head from "next/head";
import Layout from "@/components/Layout/Layout";
import AnimatedText from "@/components/animatedText/AnimatedText";
import Link from "next/link";
import Image from "next/image";
import PaginationImage from "../../public/images/articles/pagination component in reactjs.jpg";
import { motion, useMotionValue } from "framer-motion";

const FramerImage = motion(Image);

const MovingImage = ({ title, img, link }) => {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const imgRef = useRef(null);

  const handleMouseMove = (event) => {
    imgRef.current.style.display = "inline-block";
    x.set(event.pageX);
    y.set(-10);
  };
  const handleMouseLeave = (event) => {
    imgRef.current.style.display = "none";
    x.set(0);
    y.set(0);
  };

  return (
    <Link
      href={link}
      className=""
      target="_blank"
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
    >
      <h2 className="font-semibold capitalize text-xl hover:underline">
        {title}
      </h2>
      <FramerImage
        ref={imgRef}
        src={img}
        alt={title}
        style={{ x, y }}
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1, transition: { duration: 0.5 } }}
        className="w-96 h-auto hidden absolute rounded-lg z-40"
      />
    </Link>
  );
};

const Article = ({ image, title, date, link }) => {
  return (
    <motion.li
      initial={{ y: 200 }}
      whileInView={{ y: 0, transition: 1 }}
      viewport={{ once: true }}
      className="w-full p-4 py-6 rounded-xl flex items-center justify-between bg-light dark:bg-dark text-dark dark:text-light first:mt-0 border border-solid border-dark dark:border-light border-b-4 border-r-4"
    >
      <MovingImage title={title} img={image} link={link} />
      <span className="text-primary dark:text-primaryDark font-semibold pl-4">{date}</span>
    </motion.li>
  );
};

const FeaturedArticle = ({ img, title, link, summary, duration }) => {
  return (
    <li className="w-full rounded-3xl border border-solid border-dark dark:border-light bg-light dark:bg-dark shadow-2xl relative">
      <div className="p-6 rounded-xl space-y-2">
        <div className="absolute top-0 -right-3 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light -z-10" />
        <Link
          href={link}
          target="_blank"
          className="w-1/2 cursor-pointer overflow-hidden"
        >
          <div className="rounded-xl overflow-hidden">
            <FramerImage
              src={img}
              alt={title}
              whileHover={{
                scale: 1.05,
                transition: { duration: 0.2 },
              }}
              className="w-full h-auto rounded-xl "
            />
          </div>
        </Link>

        <div className="relative w-full flex flex-col justify-between items-start space-y-4">
          <Link href={link} target="_blank" className="hover:underline">
            <h3 className="my-2 w-full text-4xl font-bold text-left text-dark dark:text-light">
              {title}
            </h3>
          </Link>
          <p className="my-2 font-medium text-dark/75 dark:text-light/75">{summary}</p>

          <span className="text-primary dark:text-primaryDark">{duration} min read</span>
        </div>
      </div>
    </li>
  );
};

const articles = () => {
  return (
    <>
      <Head>
        <title>Niloy Kumar || Articles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <main className="flex w-full flex-col items-center justify-center text-dark dark:text-light bg-light dark:bg-dark">
        <Layout className="!pt-16 !mb-28">
          <AnimatedText text="Words Can Change The World!" className="mb-16" />

          <ul className="w-full grid grid-cols-2 gap-16">
            <FeaturedArticle
              img={PaginationImage}
              title="Build A Custom Pagination Component In Reactjs From Scratch"
              summary={`Learn how to build a custom pagination component in ReactJS from scratch. Follow this step-by-step guide to integrate Pagination component in your ReactJS project.`}
              duration={9}
              link={"/"}
            />

            <FeaturedArticle
              img={PaginationImage}
              title="Build A Custom Pagination Component In Reactjs From Scratch"
              summary={`Learn how to build a custom pagination component in ReactJS from scratch. Follow this step-by-step guide to integrate Pagination component in your ReactJS project.`}
              duration={9}
              link={"/"}
            />
          </ul>

          <h2 className="font-bold text-4xl w-full text-center mt-32 mb-16">
            All Articles
          </h2>
          <ul className=" mb-44 space-y-4">
            <Article
              title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
              link=""
              image={PaginationImage}
              date="January 27, 2023"
            />
            <Article
              title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
              link=""
              image={PaginationImage}
              date="January 27, 2023"
            />
            <Article
              title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
              link=""
              image={PaginationImage}
              date="January 27, 2023"
            />
            <Article
              title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
              link=""
              image={PaginationImage}
              date="January 27, 2023"
            />
            <Article
              title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
              link=""
              image={PaginationImage}
              date="January 27, 2023"
            />
          </ul>
        </Layout>
      </main>
    </>
  );
};

export default articles;
