import Layout from "@/components/Layout/Layout";
import NavBar from "@/components/nav/NavBar";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../assets/images/developer-pic-1.png";
import AnimatedText from "@/components/animatedText/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/assets/svg/LinkArrow";
import HireMe from "@/components/hireme/HireMe";
import LightBulb from "../assets/svg/LightBulb";

export default function Home() {
  return (
    <>
      <Head>
        <title>Niloy kumar || Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className="text-dark w-full min-h-[calc(100vh_-_96px)]">
          <Layout className="center-container-elements space-x-4">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Profile picture"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left"
              />
              <span className="my-4 text-base font-medium text-dark dark:text-light ">
                As a skilled web3 developer, I am dedicated to turning ideas
                into innovative web applications. Explore my latest projects and
                articles, showcasing my expertise in React.js and web
                development.
              </span>
              <div className="space-x-4 flex items-center mt-2 self-start">
                <Link
                  href={`/dummy.pdf`}
                  target="_blank"
                  className="flex items-center bg-dark text-light dark:bg-light dark:text-dark px-6 py-2 rounded-lg font-semibold text-lg hover:text-dark hover:bg-light dark:hover:bg-dark dark:hover:text-light border-solid border-2 border-transparent hover:border-dark dark:hover:border-light hover:border-2"
                  download={true}
                >
                  <span>Resume</span> <LinkArrow className="ml-1 w-6" />
                </Link>
                <Link
                  href={`mailto:imniloy8@gmail.com`}
                  target="_blank"
                  className="ml-4 underline capitalize text-lg font-semibold text-dark dark:text-light"
                >
                  Contact
                </Link>
              </div>
            </div>
          </Layout>
          <HireMe />

          <div className="absolute right-8 bottom-8 inline-block w-24">
            <LightBulb className="w-full h-auto" />
          </div>
        </section>
      </main>
    </>
  );
}
