import Layout from "@/components/Layout/Layout";
import AnimatedText from "@/components/animatedText/AnimatedText";
import GithubIcon from "@/components/assets/svgs/GithubIcon";
import NavBar from "@/components/nav/NavBar";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import CryptOProjectImage from "../../public/images/projects/crypto-screener-cover-image.jpg";
import NftProjectImage from "../../public/images/projects/nft-collection-website-cover-image.jpg";
import { motion } from "framer-motion";

const FeaturedProject = ({ type, title, summary, img, link, github }) => {
  return (
    <div className="w-full flex items-center justify-between rounded-3xl border border-solid border-dark dark:border-light bg-light dark:bg-dark shadow-2xl relative rounded-br-2xl">
      <div className="flex items-center justify-between p-10 rounded-xl rounded-br-3xl">
        <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] dark:bg-light bg-dark" />
        <Link
          href={link}
          target="_blank"
          className="w-1/2 cursor-pointer overflow-hidden"
        >
          <div className=" rounded-xl overflow-hidden">
            <motion.div
              className="w-full"
              whileHover={{
                scale: 1.05,
                transition: { duration: 0.5 },
              }}
            >
              <Image
                src={img}
                alt={title}
                className="w-full h-auto rounded-xl "
              />
            </motion.div>
          </div>
        </Link>

        <div className="w-1/2 flex flex-col justify-between items-start pl-6">
          <span className="font-semibold text-primary dark:text-primaryDark text-xl">
            {type}
          </span>
          <Link href={link} target="_blank" className="hover:underline">
            <h3 className="my-2 w-full text-4xl font-bold text-left text-dark dark:text-light">
              {title}
            </h3>
          </Link>
          <p className="my-2 font-medium text-dark dark:text-light/75">
            {summary}
          </p>

          <div className="mt-2 flex items-center space-x-5">
            <Link href={github} target="_blank">
              <GithubIcon className="w-12 h-12" />
            </Link>
            <Link
              href={github}
              target="_blank"
              className="py-4 px-6 bg-dark text-light dark:bg-light dark:text-dark font-semibold rounded-lg"
            >
              Visit the Project
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

const Project = ({ type, title, img, link, github }) => {
  return (
    <div className="w-full rounded-3xl border border-solid border-dark dark:border-light bg-light dark:bg-dark shadow-2xl relative">
      <div className="p-6 rounded-xl space-y-2">
        <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light" />
        <Link
          href={link}
          target="_blank"
          className="w-1/2 cursor-pointer overflow-hidden"
        >
          <div className=" rounded-xl overflow-hidden">
            <motion.div
              className="w-full"
              whileHover={{
                scale: 1.05,
                transition: { duration: 0.5 },
              }}
            >
              <Image
                src={img}
                alt={title}
                className="w-full h-auto rounded-xl "
              />
            </motion.div>
          </div>
        </Link>

        <div className="w-full flex flex-col justify-between items-start">
          <span className="font-semibold text-primary dark:text-primaryDark text-xl">
            {type}
          </span>
          <Link href={link} target="_blank" className="hover:underline">
            <h3 className="my-2 w-full text-4xl font-bold text-left text-dark dark:text-light">
              {title}
            </h3>
          </Link>

          <div className="mt-2 flex items-center justify-between w-full space-x-5">
            <Link href={github} target="_blank">
              <GithubIcon className="w-9 h-9" />
            </Link>
            <Link
              href={github}
              target="_blank"
              className="font-semibold text-lg text-primary dark:text-primaryDark"
            >
              Visit the Project
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

const projects = () => {
  return (
    <>
      <Head>
        <title>Niloy Kumar || Projects Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <main className="flex w-full flex-col items-center justify-center pb-16 text-dark dark:text-light bg-light dark:bg-dark">
        <Layout className="!pt-16">
          <AnimatedText
            text="Imagination Trumps Knowledge!"
            className="mb-16 mx-52"
          />

          <div className="grid grid-cols-12 gap-24">
            <div className="col-span-12">
              <FeaturedProject
                type={`Featured Project`}
                title="Crypto Screener Application"
                summary={`A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your local currency.`}
                // img={`/images/fashion-studio-website.jpg`}
                img={CryptOProjectImage}
                link={`https://devdreaming.com/videos/build-crypto-screener-app-with-react-tailwind-css`}
                github="/"
              />
            </div>
            <div className="col-span-6">
              <Project
                type={`Website Template`}
                title="NFT collection Website"
                img={NftProjectImage}
                link={`/`}
                github="/"
              />
            </div>
            <div className="col-span-6">
              <Project
                type={`Website Template`}
                title="NFT collection Website"
                img={NftProjectImage}
                link={`/`}
                github="/"
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                type={`Featured Project`}
                title="Crypto Screener Application"
                summary={`A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your local currency.`}
                img={CryptOProjectImage}
                link={`https://devdreaming.com/videos/build-crypto-screener-app-with-react-tailwind-css`}
                github="/"
              />
            </div>
            <div className="col-span-6">
              <Project
                type={`Website Template`}
                title="NFT collection Website"
                img={NftProjectImage}
                link={`/`}
                github="/"
              />
            </div>
            <div className="col-span-6">
              <Project
                type={`Website Template`}
                title="NFT collection Website"
                img={NftProjectImage}
                link={`/`}
                github="/"
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                type={`Featured Project`}
                title="Crypto Screener Application"
                summary={`A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your local currency.`}
                img={CryptOProjectImage}
                link={`https://devdreaming.com/videos/build-crypto-screener-app-with-react-tailwind-css`}
                github="/"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default projects;
